## Let's make a LogisticRegression

**Didn't work very well**

In [2]:
import pandas as pd
import numpy as np
import requests
import json

In [3]:
df_matches_grouped = pd.read_pickle("../data/df_matches_grouped.pkl")

In [4]:
model_df = df_matches_grouped[["match_id", "radiant_1", "radiant_2", "radiant_3", "radiant_4", "radiant_5", "dire_1", "dire_2", "dire_3", "dire_4", "dire_5"]]
target_df = df_matches_grouped["radiant_win"]
model_df

,match_id,radiant_1,radiant_2,radiant_3,radiant_4,radiant_5,dire_1,dire_2,dire_3,dire_4,dire_5
0,5510478612,7,70,8,30,105,119,73,90,31,18
1,5510478615,86,49,84,75,57,40,120,30,1,60
2,5510478700,108,71,8,26,47,59,74,30,21,14
3,5510478702,34,8,10,86,53,48,18,25,85,75
4,5510478708,67,22,37,107,14,74,7,84,45,44
...,...,...,...,...,...,...,...,...,...,...,...
99995,5513436913,69,63,84,7,44,2,45,22,27,73
99996,5513436918,86,53,1,19,84,104,39,113,26,54
99997,5513437003,15,108,21,30,53,126,104,110,4,84
99998,5513437208,27,93,6,84,81,10,67,120,101,104
99999,5513437212,25,4,96,75,46,80,29,39,8,84

In [5]:
feature_set = ["radiant_1", "radiant_2", "radiant_3", "radiant_4", "radiant_5", "dire_1", "dire_2", "dire_3", "dire_4", "dire_5",]

radiant_features = (pd.get_dummies(model_df["radiant_1"], prefix="radiant") 
 + pd.get_dummies(model_df["radiant_2"], prefix="radiant")
 + pd.get_dummies(model_df["radiant_3"], prefix="radiant")
 + pd.get_dummies(model_df["radiant_4"], prefix="radiant")
 + pd.get_dummies(model_df["radiant_5"], prefix="radiant"))

dire_features = (pd.get_dummies(model_df["dire_1"], prefix="dire") 
 + pd.get_dummies(model_df["dire_2"], prefix="dire")
 + pd.get_dummies(model_df["dire_3"], prefix="dire")
 + pd.get_dummies(model_df["dire_4"], prefix="dire")
 + pd.get_dummies(model_df["dire_5"], prefix="dire"))

model_df = pd.concat([radiant_features, dire_features], axis=1)

In [6]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(model_df, target_df, test_size=0.1)

In [7]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [8]:
train_predictions = model.predict(X_train)
test_predictions = model.predict(X_test)

In [9]:
X_train["predictions"] = train_predictions.tolist()
X_train["target"] = y_train

X_test["predictions"] = test_predictions.tolist()
X_test["target"] = y_test

<ipython-input-9-f29b54f2fe9d>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train["predictions"] = train_predictions.tolist()
<ipython-input-9-f29b54f2fe9d>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train["target"] = y_train
<ipython-input-9-f29b54f2fe9d>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test["predictions"] = test_predictions.tolist()
<ipython-input-9-f29b54f2fe9d>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test["target"] = y_test

In [10]:
X_train.head(100)

,radiant_1,radiant_2,radiant_3,radiant_4,radiant_5,radiant_6,radiant_7,radiant_8,radiant_9,radiant_10,...,dire_113,dire_114,dire_119,dire_120,dire_121,dire_126,dire_128,dire_129,predictions,target
54401,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,False,False
72257,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,True,True
75931,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,False,False
62439,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,False,False
96103,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95434,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,True,True
33426,0,0,0,0,0,0,0,0,0,1,...,0,1,0,0,0,0,0,0,False,False
12818,0,0,0,0,0,0,0,1,1,0,...,0,0,0,0,0,0,0,0,True,True
32260,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,True,True
22340,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,False,False

In [11]:
X_train["prediction_correct"] = np.where(X_train["predictions"] == X_train["target"], 1, 0)

X_train["prediction_correct"].sum() / len(X_train["prediction_correct"])

<ipython-input-11-eb5865d41a71>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train["prediction_correct"] = np.where(X_train["predictions"] == X_train["target"], 1, 0)

0.5765222222222223

In [12]:
X_test["prediction_correct"] = np.where(X_test["predictions"] == X_test["target"], 1, 0)

X_test["prediction_correct"].sum() / len(X_test["prediction_correct"])

<ipython-input-12-2c6a6217677a>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test["prediction_correct"] = np.where(X_test["predictions"] == X_test["target"], 1, 0)

0.5793